[build]
buildCommand = "npm install && npm install --prefix portal-server"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
