// Generated by scripts/sync-deploy-config.js.
// On this LAN/localhost, talk to the local portal-server. On Cloudflare Pages, use /api (Cloudflare Pages Function → Railway).
(function () {
  var host = typeof location !== "undefined" ? location.hostname : "";
  var port = typeof location !== "undefined" ? location.port : "";

  function isDeployedHost(h) {
    return (
      /(^|\.)gzlawfirm\.net$/i.test(h) ||
      /(^|\.)pages\.dev$/i.test(h) ||
      /(^|\.)workers\.dev$/i.test(h) ||
      /(^|\.)vercel\.app$/i.test(h) ||
      /(^|\.)railway\.app$/i.test(h)
    );
  }

  if (host && !isDeployedHost(host)) {
    window.PORTAL_API_BASE = port === "3000" || port === "" ? "" : "http://" + host + ":3000/api";
    return;
  }
  window.PORTAL_API_BASE = "";
})();
